version: '3.8'

services:
  gutenberg-extractor:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - PYTHONUNBUFFERED=1
    networks:
      - gutenberg-network

networks:
  gutenberg-network:
    driver: bridge
